In [5]:
%matplotlib inline
import pandas as pd

In [6]:
from IPython.core.display import HTML
css = open('style-table.css').read() + open('style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

In [10]:
# titles = pd.read_csv('data/titles.csv')
titles = pd.read_csv(r'C:\Users\sdiou\Downloads\pycon-pandas-tutorial-master\pycon-pandas-tutorial-master\data\titles.csv')
titles.head()

                      title  year
0                 Doux amer  1989
1  Jiu wu tuo qiang nu jing  1995
2             Breaking Hart  2013
3                    Alamid  1967
4         The Learning Tree  1969

In [14]:
# cast = pd.read_csv('data/cast.csv')
cast = pd.read_csv(r'C:\Users\sdiou\Downloads\pycon-pandas-tutorial-master\pycon-pandas-tutorial-master\data\cast.csv', encoding = 'utf-8')
cast.head()

                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

### How many movies are listed in the titles dataframe?

In [19]:
titles.head()

                      title  year
0                 Doux amer  1989
1  Jiu wu tuo qiang nu jing  1995
2             Breaking Hart  2013
3                    Alamid  1967
4         The Learning Tree  1969

In [23]:
titles.tail()

                             title  year
226008               Yankesici kiz  1964
226009         Night in Montmartre  1931
226010         Kapitanskaya dochka  1928
226011  The Monkey King's Daughter  2018
226012             Mark Six Comedy  2004

### Filtering
let's you reduce donw to a criterion

In [38]:
h

                                               title  year
0                                          Doux amer  1989
1                           Jiu wu tuo qiang nu jing  1995
2                                      Breaking Hart  2013
3                                             Alamid  1967
4                                  The Learning Tree  1969
5                                      Just Tell Her  2017
6  The Incredible Adventure of Jojo (And His Anno...  2014
7                        La ragazza del vagone letto  1980

In [ ]:
turn year into decade
h.year // 10 * 10

0    1980
1    1990
2    2010
3    1960
4    1960
5    2010
6    2010
7    1980
Name: year, dtype: int64

In [37]:
h.year > 1985

0     True
1     True
2     True
3    False
4    False
5     True
6     True
7    False
Name: year, dtype: bool

In [ ]:
h[(h.year <= 1980) | (h.year>= 2000)]

                                               title  year
2                                      Breaking Hart  2013
3                                             Alamid  1967
4                                  The Learning Tree  1969
5                                      Just Tell Her  2017
6  The Incredible Adventure of Jojo (And His Anno...  2014
7                        La ragazza del vagone letto  1980

In [51]:
titles

                             title  year
0                        Doux amer  1989
1         Jiu wu tuo qiang nu jing  1995
2                    Breaking Hart  2013
3                           Alamid  1967
4                The Learning Tree  1969
...                            ...   ...
226008               Yankesici kiz  1964
226009         Night in Montmartre  1931
226010         Kapitanskaya dochka  1928
226011  The Monkey King's Daughter  2018
226012             Mark Six Comedy  2004

[226013 rows x 2 columns]

In [55]:
t = titles
t[t.title == 'Macbeth'].sort_values('year').tail()

          title  year
64363   Macbeth  2013
93878   Macbeth  2014
86763   Macbeth  2015
174025  Macbeth  2017
78368   Macbeth  2018

In [59]:
h = cast.head()
h = h[h.n.notnull()]
# h[h.n.isnull()]
h

                 title  year      name   type        character     n
0       Closet Monster  2015  Buffy #1  actor          Buffy 4  31.0
1      Suuri illusioni  1985    Homo $  actor           Guests  22.0
2  Battle of the Sexes  2017   $hutter  actor  Bobby Riggs Fan  10.0

In [ ]:
# How many movies are listed in the titles dataframe?
print("there are " + str(len(titles)) + " in the data base")

there are 226013 in the data base

### What are the earliest two films listed in the titles dataframe?

In [65]:
titles.sort_values('year', ascending=True).head(2)

                     title  year
37137           Miss Jerry  1894
113960  The Startled Lover  1898

### How many movies have the single-word title "Hamlet"?

In [67]:
len(titles[t.title == 'Hamlet'] )

20

### How many movies are titled "North by Northwest"?

In [68]:
len(titles[t.title == 'North by Northwest'] )

1

### When was the first movie titled "Hamlet" made?

In [71]:
titles[t.title == 'Hamlet'].sort_values('year').head(1)

         title  year
210546  Hamlet  1910

### List all of the "Treasure Island" movies from earliest to most recent.

In [72]:
titles[t.title == 'Treasure Island'].sort_values('year')

                  title  year
22242   Treasure Island  1918
163882  Treasure Island  1920
191181  Treasure Island  1934
189545  Treasure Island  1950
5708    Treasure Island  1972
64797   Treasure Island  1973
153281  Treasure Island  1985
194516  Treasure Island  1999

### How many movies were made in the year 1950?

In [74]:
len(titles[t.year == 1950])

1109

### How many movies were made in the year 1960?

In [75]:
len(titles[t.year == 1960])

1496

### How many movies were made from 1950 through 1959?

In [78]:
len (titles[ (titles.year >= 1950) & (titles.year <1960)] )

12664

### In what years has a movie titled "Batman" been released?

In [79]:
titles [t.title == 'Batman']

         title  year
84535   Batman  1989
187455  Batman  1943

### How many roles were there in the movie "Inception"?

In [82]:
len(cast[cast.title == 'Inception'])

78

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [95]:
c = cast
i = c[(c.title == 'Inception') & (c.n.isnull())]
len(i)
# h[h.n.isnull()]
# h

27

51

### But how many roles in the movie "Inception" did receive an "n" value?

In [ ]:
c = cast
i = c[(c.title == 'Inception') & (c.n.notnull())]
len(i)

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [100]:
c = cast
i = c[(c.title == 'North by Northwest') & (c.n.notnull())].sort_values('n')
i

,title,year,name,type,character,n
797150,North by Northwest,1959,Cary Grant,actor,Roger O. Thornhill,1.0
3201980,North by Northwest,1959,Eva Marie Saint,actress,Eve Kendall,2.0
1333732,North by Northwest,1959,James Mason,actor,Phillip Vandamm,3.0
2878461,North by Northwest,1959,Jessie Royce Landis,actress,Clara Thornhill,4.0
326415,North by Northwest,1959,Leo G. Carroll,actor,The Professor,5.0
2780220,North by Northwest,1959,Josephine Hutchinson,actress,Mrs. Townsend,6.0
1551491,North by Northwest,1959,Philip Ober,actor,Lester Townsend,7.0
1167105,North by Northwest,1959,Martin Landau,actor,Leonard,8.0
2239203,North by Northwest,1959,Adam Williams,actor,Valerian,9.0
1657968,North by Northwest,1959,Edward Platt,actor,Victor Larrabee,10.0
609229,North by Northwest,1959,Robert Ellenstein,actor,Licht,11.0
2100440,North by Northwest,1959,Les Tremayne,actor,Auctioneer,12.0
425645,North by Northwest,1959,Philip Coolidge,actor,Dr. Cross,13.0
1379980,North by Northwest,1959,Patrick McVey,actor,Sergeant Flamm,14.0
189719,North by Northwest,1959,Edward Binns,actor,Captain Junket,15.0
1267109,North by Northwest,1959,Ken Lynch,actor,Charley - Chicago Policeman,16.0

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [104]:
c = cast
s = c[(c.title == 'Sleuth') & (s.year == 1972)]
s = s.sort_values('n')
s

,title,year,name,type,character,n
1560814,Sleuth,1972,Laurence Olivier,actor,Andrew Wyke,1.0
299291,Sleuth,1972,Michael Caine,actor,Milo Tindle,2.0
342151,Sleuth,1972,Alec Cawthorne,actor,Inspector Doppler,3.0
1341313,Sleuth,1972,John (II) Matthews,actor,Detective Sergeant Tarrant,4.0
2490141,Sleuth,1972,Eve (III) Channing,actress,Marguerite Wyke,5.0
1325945,Sleuth,1972,Teddy Martin,actor,Police Constable Higgs,6.0

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [108]:
c = cast
s = c[(c.title == 'Sleuth') & (c.year == 2007)]
s = s.sort_values('n')
s

          title  year                 name     type          character    n
299292   Sleuth  2007        Michael Caine    actor             Andrew  1.0
1183659  Sleuth  2007             Jude Law    actor               Milo  2.0
1652936  Sleuth  2007        Harold Pinter    actor        Man on T.V.  3.0
238747   Sleuth  2007      Kenneth Branagh    actor  Other Man on T.V.  NaN
342152   Sleuth  2007  Alec (II) Cawthorne    actor  Inspector Doppler  NaN
2490140  Sleuth  2007    Eve (II) Channing  actress    Marguerite Wyke  NaN
3069393  Sleuth  2007    Carmel O'Sullivan  actress             Maggie  NaN

### How many roles were credited in the silent 1921 version of Hamlet?

In [112]:
c = cast
c = c [(c.title == 'Hamlet') & (c.year == 1921) ]
len (c.character)

9

### How many roles were credited in Branagh’s 1996 Hamlet?

In [117]:
c = cast
c = c [(c.title == 'Hamlet') & (c.year == 1996)]
len(c)

54

### How many "Hamlet" roles have been listed in all film credits through history?

In [120]:
c = cast
c = c [ (c.character == 'Hamlet')]
len(c)

93

### How many people have played an "Ophelia"?

In [121]:
c = cast
c = c [ (c.character == 'Ophelia')]
len(c)

102

In [128]:
c = cast
c = c [ (c.character == 'Ophelia')] #.name.unique()
len (c.name.unique() )

101

### How many people have played a role called "The Dude"?

In [131]:
c = cast
c = c [ (c.character == 'The Dude')] #.name.unique()
len (c.name.unique() )
# c

17

### How many people have played a role called "The Stranger"?

In [133]:
c = cast
c = c [ (c.character == 'The Stranger')] #.name.unique()
len (c.name.unique() )

160

In [134]:
# solution

# How many people have played a role called "The Stranger"?

c = cast
len(c[c.character == 'The Stranger'].name.unique())

160

### How many roles has Sidney Poitier played throughout his career?

In [137]:
c = cast
c = c [ (c.name == 'Sidney Poitier')] #.name.unique()
len (c.character.unique() )
# c

41

### How many roles has Judi Dench played?

In [142]:
c = cast
c = c [ (c.name == 'Judi Dench')] #.name.unique()
len (c.character.unique() )
# len (c.character )

46

In [140]:
# How many roles has Judi Dench played?

c = cast
c = c[c.name == 'Judi Dench']
len(c)

55

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [164]:
c = cast
c = c [ (c.name == 'Cary Grant')] #.name.unique()
# len (c.character.unique() )
c = c [c.year.notnull()]
# c[c.year] // 10 * 10
c = (c[c.n == 2])
c = c [ (c.year // 10 * 10 == 1940)].sort_values('year')
c

                   title  year        name   type    character    n
797147  My Favorite Wife  1940  Cary Grant  actor   Nick Arden  2.0
797157    Penny Serenade  1941  Cary Grant  actor  Roger Adams  2.0

### List the leading roles that Cary Grant played in the 1940s in order by year.

### How many roles were available for actors in the 1950s?

### How many roles were available for actresses in the 1950s?

### How many leading roles (n=1) were available from the beginning of film history through 1980?

### How many non-leading roles were available through from the beginning of film history through 1980?

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?